import type { ToolDefinition } from "./types";
import { fuzzySearchTools } from "./fuzzy-search";

export const TOOL_REGISTRY: ToolDefinition[] = [
  // P0 — MVP
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON",
    category: "format",
    priority: "P0",
    icon: "Braces",
    keywords: ["json", "format", "validate", "minify", "pretty"],
    smartDetect: /^[\s]*[{[]/,
  },
  {
    id: "base64",
    name: "Base64 Encode/Decode",
    description: "Encode and decode Base64 strings",
    category: "encode",
    priority: "P0",
    icon: "Binary",
    keywords: ["base64", "encode", "decode", "b64"],
    smartDetect: /^[A-Za-z0-9+/]+=*$/,
  },
  {
    id: "url-encode",
    name: "URL Encode/Decode",
    description: "Encode and decode URL strings",
    category: "encode",
    priority: "P0",
    icon: "Link",
    keywords: ["url", "encode", "decode", "percent", "uri"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "generate",
    priority: "P0",
    icon: "Hash",
    keywords: ["hash", "md5", "sha", "sha256", "checksum"],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4)",
    category: "generate",
    priority: "P0",
    icon: "Fingerprint",
    keywords: ["uuid", "guid", "generate", "random", "v4"],
  },
  {
    id: "unix-time",
    name: "Unix Time Converter",
    description: "Convert Unix timestamps to human-readable dates",
    category: "inspect",
    priority: "P0",
    icon: "Clock",
    keywords: ["unix", "timestamp", "epoch", "time", "date"],
    smartDetect: /^\d{10,13}$/,
  },
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    description: "Decode and inspect JWT tokens",
    category: "inspect",
    priority: "P0",
    icon: "Shield",
    keywords: ["jwt", "token", "decode", "json web token", "bearer"],
    smartDetect: /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/,
  },
  {
    id: "regex-tester",
    name: "RegExp Tester",
    description: "Test and debug regular expressions",
    category: "inspect",
    priority: "P0",
    icon: "Regex",
    keywords: ["regex", "regexp", "regular expression", "pattern", "match"],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL color formats",
    category: "convert",
    priority: "P0",
    icon: "Palette",
    keywords: ["color", "hex", "rgb", "hsl", "convert"],
  },
  {
    id: "number-base",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, hexadecimal",
    category: "convert",
    priority: "P0",
    icon: "Calculator",
    keywords: ["binary", "hex", "decimal", "octal", "base", "radix"],
  },
  {
    id: "case-converter",
    name: "String Case Converter",
    description: "Convert between camelCase, snake_case, kebab-case, and more",
    category: "convert",
    priority: "P0",
    icon: "CaseSensitive",
    keywords: ["case", "camelcase", "snake_case", "kebab-case", "pascal"],
  },
  {
    id: "line-sort",
    name: "Line Sort/Dedupe",
    description: "Sort lines and remove duplicates",
    category: "format",
    priority: "P0",
    icon: "ListOrdered",
    keywords: ["sort", "dedupe", "lines", "unique", "order"],
  },

  // P1 — Core
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description: "Beautify and minify HTML",
    category: "format",
    priority: "P1",
    icon: "Code",
    keywords: ["html", "format", "beautify", "minify"],
  },
  {
    id: "css-formatter",
    name: "CSS Formatter",
    description: "Beautify and minify CSS",
    category: "format",
    priority: "P1",
    icon: "Paintbrush",
    keywords: ["css", "format", "beautify", "minify"],
  },
  {
    id: "js-formatter",
    name: "JS Formatter",
    description: "Beautify and minify JavaScript",
    category: "format",
    priority: "P1",
    icon: "FileCode",
    keywords: ["javascript", "js", "format", "beautify", "minify"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format SQL queries with syntax highlighting",
    category: "format",
    priority: "P1",
    icon: "Database",
    keywords: ["sql", "format", "query", "postgresql", "mysql"],
  },
  {
    id: "yaml-json",
    name: "YAML ↔ JSON",
    description: "Convert between YAML and JSON formats",
    category: "convert",
    priority: "P1",
    icon: "FileJson2",
    keywords: ["yaml", "json", "convert", "yml"],
  },
  {
    id: "json-csv",
    name: "JSON ↔ CSV",
    description: "Convert between JSON and CSV formats",
    category: "convert",
    priority: "P1",
    icon: "Table",
    keywords: ["json", "csv", "convert", "spreadsheet"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two texts and find differences",
    category: "inspect",
    priority: "P1",
    icon: "GitCompare",
    keywords: ["diff", "compare", "text", "difference"],
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Live preview of markdown content",
    category: "inspect",
    priority: "P1",
    icon: "FileText",
    keywords: ["markdown", "md", "preview", "render"],
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse and explain cron expressions",
    category: "inspect",
    priority: "P1",
    icon: "Timer",
    keywords: ["cron", "schedule", "parser", "crontab"],
  },
  {
    id: "url-parser",
    name: "URL Parser",
    description: "Parse URL into components",
    category: "convert",
    priority: "P1",
    icon: "Globe",
    keywords: ["url", "parse", "uri", "components"],
    smartDetect: /^https?:\/\//,
  },
  {
    id: "html-entity",
    name: "HTML Entity Encode/Decode",
    description: "Encode and decode HTML entities",
    category: "encode",
    priority: "P1",
    icon: "Code2",
    keywords: ["html", "entity", "encode", "decode", "ampersand"],
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text",
    category: "generate",
    priority: "P1",
    icon: "Text",
    keywords: ["lorem", "ipsum", "placeholder", "text", "dummy"],
  },
  {
    id: "random-string",
    name: "Random String Generator",
    description: "Generate random strings with custom charset",
    category: "generate",
    priority: "P1",
    icon: "Shuffle",
    keywords: ["random", "string", "password", "generate"],
  },
  {
    id: "hex-ascii",
    name: "Hex ↔ ASCII",
    description: "Convert between hex and ASCII strings",
    category: "convert",
    priority: "P1",
    icon: "Hexagon",
    keywords: ["hex", "ascii", "convert", "hexadecimal"],
    smartDetect: /^[0-9a-fA-F\s]+$/,
  },
  {
    id: "string-inspector",
    name: "String Inspector",
    description: "Analyze text statistics and character codes",
    category: "inspect",
    priority: "P1",
    icon: "ScanSearch",
    keywords: ["string", "inspect", "analyze", "length", "encoding"],
  },

  // P2 — Extended
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Beautify and minify XML",
    category: "format",
    priority: "P2",
    icon: "FileCode2",
    keywords: ["xml", "format", "beautify", "minify"],
  },
  {
    id: "html-jsx",
    name: "HTML → JSX",
    description: "Convert HTML markup to React JSX",
    category: "convert",
    priority: "P2",
    icon: "Component",
    keywords: ["html", "jsx", "react", "convert"],
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    description: "Render HTML in a sandboxed preview",
    category: "inspect",
    priority: "P2",
    icon: "Monitor",
    keywords: ["html", "preview", "render"],
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs",
    category: "generate",
    priority: "P2",
    icon: "QrCode",
    keywords: ["qr", "qrcode", "barcode", "generate"],
  },
  {
    id: "backslash-escape",
    name: "Backslash Escape/Unescape",
    description: "Escape and unescape backslashes in strings",
    category: "encode",
    priority: "P2",
    icon: "Slash",
    keywords: ["backslash", "escape", "unescape", "string"],
  },
  {
    id: "cert-decoder",
    name: "Certificate Decoder",
    description: "Decode and inspect X.509 certificates",
    category: "inspect",
    priority: "P2",
    icon: "ShieldCheck",
    keywords: ["certificate", "x509", "ssl", "tls", "pem"],
  },
  {
    id: "svg-to-css",
    name: "SVG → CSS",
    description: "Convert SVG to CSS background-image",
    category: "convert",
    priority: "P2",
    icon: "Image",
    keywords: ["svg", "css", "background", "convert"],
  },
  {
    id: "base64-image",
    name: "Base64 Image",
    description: "Encode and preview Base64 images",
    category: "encode",
    priority: "P2",
    icon: "ImagePlus",
    keywords: ["base64", "image", "data uri", "preview"],
  },

  // P3 — Advanced
  {
    id: "curl-code",
    name: "cURL → Code",
    description: "Convert cURL commands to fetch/Python code",
    category: "convert",
    priority: "P3",
    icon: "Terminal",
    keywords: ["curl", "fetch", "http", "code", "python"],
  },
  {
    id: "json-to-code",
    name: "JSON → Code",
    description: "Generate TypeScript or Go types from JSON",
    category: "convert",
    priority: "P3",
    icon: "Brackets",
    keywords: ["json", "typescript", "go", "code", "generate"],
  },
  {
    id: "php-serialize",
    name: "PHP Serialize/Unserialize",
    description: "Serialize and unserialize PHP data structures",
    category: "convert",
    priority: "P3",
    icon: "PHP",
    keywords: ["php", "serialize", "unserialize"],
  },
  {
    id: "erb-formatter",
    name: "ERB Formatter",
    description: "Beautify ERB templates",
    category: "format",
    priority: "P3",
    icon: "FileCode",
    keywords: ["erb", "ruby", "template", "format"],
  },
  {
    id: "less-formatter",
    name: "LESS Formatter",
    description: "Beautify LESS stylesheets",
    category: "format",
    priority: "P3",
    icon: "Paintbrush",
    keywords: ["less", "css", "format"],
  },
  {
    id: "scss-formatter",
    name: "SCSS Formatter",
    description: "Beautify SCSS stylesheets",
    category: "format",
    priority: "P3",
    icon: "Paintbrush",
    keywords: ["scss", "sass", "css", "format"],
  },
  {
    id: "ulid-generator",
    name: "ULID Generator",
    description: "Generate and decode ULIDs",
    category: "generate",
    priority: "P3",
    icon: "Fingerprint",
    keywords: ["ulid", "generate", "decode", "sortable"],
  },
  {
    id: "query-string",
    name: "Query String ↔ JSON",
    description: "Convert between query strings and JSON",
    category: "convert",
    priority: "P3",
    icon: "Link2",
    keywords: ["query", "string", "url", "params", "json"],
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOL_REGISTRY.find((t) => t.id === id);
}

export function getToolsByCategory(category: ToolDefinition["category"]): ToolDefinition[] {
  return TOOL_REGISTRY.filter((t) => t.category === category);
}

export function getToolsByPriority(priority: ToolDefinition["priority"]): ToolDefinition[] {
  return TOOL_REGISTRY.filter((t) => t.priority === priority);
}

export function searchTools(query: string): ToolDefinition[] {
  return fuzzySearchTools(query, TOOL_REGISTRY).map((r) => r.tool);
}

export { fuzzySearchTools, fuzzyMatch, type ToolSearchResult } from "./fuzzy-search";
