import type { ToolDefinition } from "./types";
import { fuzzySearchTools } from "./fuzzy-search";

export const TOOL_REGISTRY: ToolDefinition[] = [
  // P0 — MVP
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON",
    category: "format",
    priority: "P0",
    icon: "Braces",
    keywords: ["json", "format", "validate", "minify", "pretty"],
    smartDetect: /^[\s]*[{[]/,
  },
  {
    id: "base64",
    name: "Base64 Encode/Decode",
    description: "Encode and decode Base64 strings",
    category: "encode",
    priority: "P0",
    icon: "Binary",
    keywords: ["base64", "encode", "decode", "b64"],
    smartDetect: /^[A-Za-z0-9+/]+=*$/,
  },
  {
    id: "url-encode",
    name: "URL Encode/Decode",
    description: "Encode and decode URL strings",
    category: "encode",
    priority: "P0",
    icon: "Link",
    keywords: ["url", "encode", "decode", "percent", "uri"],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "generate",
    priority: "P0",
    icon: "Hash",
    keywords: ["hash", "md5", "sha", "sha256", "checksum"],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4)",
    category: "generate",
    priority: "P0",
    icon: "Fingerprint",
    keywords: ["uuid", "guid", "generate", "random", "v4"],
  },
  {
    id: "unix-time",
    name: "Unix Time Converter",
    description: "Convert Unix timestamps to human-readable dates",
    category: "inspect",
    priority: "P0",
    icon: "Clock",
    keywords: ["unix", "timestamp", "epoch", "time", "date"],
    smartDetect: /^\d{10,13}$/,
  },
  {
    id: "jwt-debugger",
    name: "JWT Debugger",
    description: "Decode and inspect JWT tokens",
    category: "inspect",
    priority: "P0",
    icon: "Shield",
    keywords: ["jwt", "token", "decode", "json web token", "bearer"],
    smartDetect: /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/,
  },
  {
    id: "regex-tester",
    name: "RegExp Tester",
    description: "Test and debug regular expressions",
    category: "inspect",
    priority: "P0",
    icon: "Regex",
    keywords: ["regex", "regexp", "regular expression", "pattern", "match"],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL color formats",
    category: "convert",
    priority: "P0",
    icon: "Palette",
    keywords: ["color", "hex", "rgb", "hsl", "convert"],
  },
  {
    id: "number-base",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, hexadecimal",
    category: "convert",
    priority: "P0",
    icon: "Calculator",
    keywords: ["binary", "hex", "decimal", "octal", "base", "radix"],
  },
  {
    id: "case-converter",
    name: "String Case Converter",
    description: "Convert between camelCase, snake_case, kebab-case, and more",
    category: "convert",
    priority: "P0",
    icon: "CaseSensitive",
    keywords: ["case", "camelcase", "snake_case", "kebab-case", "pascal"],
  },
  {
    id: "line-sort",
    name: "Line Sort/Dedupe",
    description: "Sort lines and remove duplicates",
    category: "format",
    priority: "P0",
    icon: "ListOrdered",
    keywords: ["sort", "dedupe", "lines", "unique", "order"],
  },

  // P1 — Core
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description: "Beautify and minify HTML",
    category: "format",
    priority: "P1",
    icon: "Code",
    keywords: ["html", "format", "beautify", "minify"],
  },
  {
    id: "css-formatter",
    name: "CSS Formatter",
    description: "Beautify and minify CSS",
    category: "format",
    priority: "P1",
    icon: "Paintbrush",
    keywords: ["css", "format", "beautify", "minify"],
  },
  {
    id: "js-formatter",
    name: "JS Formatter",
    description: "Beautify and minify JavaScript",
    category: "format",
    priority: "P1",
    icon: "FileCode",
    keywords: ["javascript", "js", "format", "beautify", "minify"],
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format SQL queries with syntax highlighting",
    category: "format",
    priority: "P1",
    icon: "Database",
    keywords: ["sql", "format", "query", "postgresql", "mysql"],
  },
  {
    id: "yaml-json",
    name: "YAML ↔ JSON",
    description: "Convert between YAML and JSON formats",
    category: "convert",
    priority: "P1",
    icon: "FileJson2",
    keywords: ["yaml", "json", "convert", "yml"],
  },
  {
    id: "json-csv",
    name: "JSON ↔ CSV",
    description: "Convert between JSON and CSV formats",
    category: "convert",
    priority: "P1",
    icon: "Table",
    keywords: ["json", "csv", "convert", "spreadsheet"],
  },
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two texts and find differences",
    category: "inspect",
    priority: "P1",
    icon: "GitCompare",
    keywords: ["diff", "compare", "text", "difference"],
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Live preview of markdown content",
    category: "inspect",
    priority: "P1",
    icon: "FileText",
    keywords: ["markdown", "md", "preview", "render"],
  },
  {
    id: "cron-parser",
    name: "Cron Parser",
    description: "Parse and explain cron expressions",
    category: "inspect",
    priority: "P1",
    icon: "Timer",
    keywords: ["cron", "schedule", "parser", "crontab"],
  },
  {
    id: "url-parser",
    name: "URL Parser",
    description: "Parse URL into components",
    category: "convert",
    priority: "P1",
    icon: "Globe",
    keywords: ["url", "parse", "uri", "components"],
    smartDetect: /^https?:\/\//,
  },
  {
    id: "html-entity",
    name: "HTML Entity Encode/Decode",
    description: "Encode and decode HTML entities",
    category: "encode",
    priority: "P1",
    icon: "Code2",
    keywords: ["html", "entity", "encode", "decode", "ampersand"],
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text",
    category: "generate",
    priority: "P1",
    icon: "Text",
    keywords: ["lorem", "ipsum", "placeholder", "text", "dummy"],
  },
  {
    id: "random-string",
    name: "Random String Generator",
    description: "Generate random strings with custom charset",
    category: "generate",
    priority: "P1",
    icon: "Shuffle",
    keywords: ["random", "string", "password", "generate"],
  },
  {
    id: "hex-ascii",
    name: "Hex ↔ ASCII",
    description: "Convert between hex and ASCII strings",
    category: "convert",
    priority: "P1",
    icon: "Hexagon",
    keywords: ["hex", "ascii", "convert", "hexadecimal"],
    smartDetect: /^[0-9a-fA-F\s]+$/,
  },
  {
    id: "string-inspector",
    name: "String Inspector",
    description: "Analyze text statistics and character codes",
    category: "inspect",
    priority: "P1",
    icon: "ScanSearch",
    keywords: ["string", "inspect", "analyze", "length", "encoding"],
  },

  // P2 — Extended
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Beautify and minify XML",
    category: "format",
    priority: "P2",
    icon: "FileCode2",
    keywords: ["xml", "format", "beautify", "minify"],
  },
  {
    id: "html-jsx",
    name: "HTML → JSX",
    description: "Convert HTML markup to React JSX",
    category: "convert",
    priority: "P2",
    icon: "Component",
    keywords: ["html", "jsx", "react", "convert"],
  },
  {
    id: "html-preview",
    name: "HTML Preview",
    description: "Render HTML in a sandboxed preview",
    category: "inspect",
    priority: "P2",
    icon: "Monitor",
    keywords: ["html", "preview", "render"],
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs",
    category: "generate",
    priority: "P2",
    icon: "QrCode",
    keywords: ["qr", "qrcode", "barcode", "generate"],
  },
  {
    id: "backslash-escape",
    name: "Backslash Escape/Unescape",
    description: "Escape and unescape backslashes in strings",
    category: "encode",
    priority: "P2",
    icon: "Slash",
    keywords: ["backslash", "escape", "unescape", "string"],
  },
  {
    id: "cert-decoder",
    name: "Certificate Decoder",
    description: "Decode and inspect X.509 certificates",
    category: "inspect",
    priority: "P2",
    icon: "ShieldCheck",
    keywords: ["certificate", "x509", "ssl", "tls", "pem"],
  },
  {
    id: "svg-to-css",
    name: "SVG → CSS",
    description: "Convert SVG to CSS background-image",
    category: "convert",
    priority: "P2",
    icon: "Image",
    keywords: ["svg", "css", "background", "convert"],
  },
  {
    id: "base64-image",
    name: "Base64 Image",
    description: "Encode and preview Base64 images",
    category: "encode",
    priority: "P2",
    icon: "ImagePlus",
    keywords: ["base64", "image", "data uri", "preview"],
  },

  // P3 — Advanced
  {
    id: "curl-code",
    name: "cURL → Code",
    description: "Convert cURL commands to fetch/Python code",
    category: "convert",
    priority: "P3",
    icon: "Terminal",
    keywords: ["curl", "fetch", "http", "code", "python"],
  },
  {
    id: "json-to-code",
    name: "JSON → Code",
    description: "Generate TypeScript or Go types from JSON",
    category: "convert",
    priority: "P3",
    icon: "Brackets",
    keywords: ["json", "typescript", "go", "code", "generate"],
  },
  {
    id: "php-serialize",
    name: "PHP Serialize/Unserialize",
    description: "Serialize and unserialize PHP data structures",
    category: "convert",
    priority: "P3",
    icon: "PHP",
    keywords: ["php", "serialize", "unserialize"],
  },
  {
    id: "erb-formatter",
    name: "ERB Formatter",
    description: "Beautify ERB templates",
    category: "format",
    priority: "P3",
    icon: "FileCode",
    keywords: ["erb", "ruby", "template", "format"],
  },
  {
    id: "less-formatter",
    name: "LESS Formatter",
    description: "Beautify LESS stylesheets",
    category: "format",
    priority: "P3",
    icon: "Paintbrush",
    keywords: ["less", "css", "format"],
  },
  {
    id: "scss-formatter",
    name: "SCSS Formatter",
    description: "Beautify SCSS stylesheets",
    category: "format",
    priority: "P3",
    icon: "Paintbrush",
    keywords: ["scss", "sass", "css", "format"],
  },
  {
    id: "ulid-generator",
    name: "ULID Generator",
    description: "Generate and decode ULIDs",
    category: "generate",
    priority: "P3",
    icon: "Fingerprint",
    keywords: ["ulid", "generate", "decode", "sortable"],
  },
  {
    id: "query-string",
    name: "Query String ↔ JSON",
    description: "Convert between query strings and JSON",
    category: "convert",
    priority: "P3",
    icon: "Link2",
    keywords: ["query", "string", "url", "params", "json"],
  },
  {
    id: "excalidraw",
    name: "Draw & Write",
    description: "Sketch diagrams, notes, and whiteboards with Excalidraw — saved locally",
    category: "generate",
    priority: "P2",
    icon: "PenTool",
    keywords: ["draw", "sketch", "diagram", "whiteboard", "excalidraw", "canvas", "write", "notes"],
  },
  // Productivity — custom UI, IndexedDB persistence
  {
    id: "todo-list",
    name: "To-Do List",
    description: "Manage daily tasks with priorities — saved locally",
    category: "productivity",
    priority: "P2",
    icon: "ListTodo",
    keywords: ["todo", "tasks", "checklist", "productivity", "list"],
  },
  {
    id: "kanban-board",
    name: "Kanban Board",
    description: "Organize work in columns with drag-and-drop — saved locally",
    category: "productivity",
    priority: "P2",
    icon: "Columns",
    keywords: ["kanban", "board", "agile", "columns", "tasks", "workflow"],
  },
  {
    id: "pomodoro",
    name: "Pomodoro Timer",
    description: "Focus with timed work and break sessions — saved locally",
    category: "productivity",
    priority: "P2",
    icon: "Timer",
    keywords: ["pomodoro", "timer", "focus", "productivity", "break"],
  },
  {
    id: "quick-notes",
    name: "Quick Notes",
    description: "Capture ideas in a simple notepad — saved locally",
    category: "productivity",
    priority: "P2",
    icon: "StickyNote",
    keywords: ["notes", "notepad", "memo", "write", "jot"],
  },
  {
    id: "stopwatch",
    name: "Stopwatch",
    description: "Track elapsed time with lap splits — saved locally",
    category: "productivity",
    priority: "P2",
    icon: "Stopwatch",
    keywords: ["stopwatch", "timer", "lap", "time", "elapsed"],
  },
  {
    id: "habit-tracker",
    name: "Habit Tracker",
    description: "Build daily habits with a simple streak tracker — saved locally",
    category: "productivity",
    priority: "P2",
    icon: "CalendarCheck",
    keywords: ["habit", "streak", "daily", "routine", "tracker"],
  },

  // ── Colour ────────────────────────────────────────────────────────────────
  {
    id: "palette-generator",
    name: "Palette Generator",
    description: "Generate beautiful colour palettes from a seed colour",
    category: "color",
    priority: "P1",
    icon: "Palette",
    keywords: ["palette", "colour", "color", "generate", "scheme", "swatch"],
  },
  {
    id: "palette-collection",
    name: "Palette Collection",
    description: "Browse a curated library of colour palettes",
    category: "color",
    priority: "P2",
    icon: "Swatch",
    keywords: ["palette", "collection", "curated", "browse", "colour", "inspiration"],
  },
  {
    id: "palette-extractor",
    name: "Palette Extractor",
    description: "Extract a dominant colour palette from any image",
    category: "color",
    priority: "P1",
    icon: "Eyedropper",
    keywords: ["palette", "extract", "image", "dominant", "colour", "quantize"],
  },
  {
    id: "pixel-picker",
    name: "Pixel Picker",
    description: "Sample colours from any image with a zoom loupe",
    category: "color",
    priority: "P1",
    icon: "Eyedropper",
    keywords: ["pixel", "picker", "eyedropper", "sample", "colour", "loupe"],
  },
  {
    id: "colorblind-sim",
    name: "Colour Blindness Simulator",
    description: "Simulate how colours appear to colour blind users",
    category: "color",
    priority: "P2",
    icon: "Eye",
    keywords: ["colourblind", "colorblind", "accessibility", "deuteranopia", "protanopia", "simulate"],
  },
  {
    id: "contrast-checker",
    name: "Contrast Checker",
    description: "Check WCAG colour contrast compliance",
    category: "color",
    priority: "P1",
    icon: "Contrast",
    keywords: ["contrast", "wcag", "accessibility", "a11y", "ratio", "aa", "aaa"],
  },
  {
    id: "gradient-generator",
    name: "Gradient Generator",
    description: "Create linear, radial, conic, and mesh gradients",
    category: "color",
    priority: "P1",
    icon: "Gradient",
    keywords: ["gradient", "linear", "radial", "conic", "mesh", "css", "background"],
  },
  {
    id: "harmony-generator",
    name: "Harmony Generator",
    description: "Generate complementary, triadic, and analogous colour harmonies",
    category: "color",
    priority: "P2",
    icon: "Palette",
    keywords: ["harmony", "complementary", "triadic", "analogous", "colour", "wheel"],
  },
  {
    id: "tailwind-shades",
    name: "Tailwind Shade Generator",
    description: "Generate a full Tailwind 50–950 colour scale from one colour",
    category: "color",
    priority: "P1",
    icon: "Swatch",
    keywords: ["tailwind", "shades", "scale", "colour", "50", "950", "tokens"],
  },

  // ── Images & Assets ───────────────────────────────────────────────────────
  {
    id: "image-editor",
    name: "Image Editor",
    description: "Crop, rotate, adjust and mark up images in the browser",
    category: "image",
    priority: "P1",
    icon: "Crop",
    keywords: ["editor", "image", "crop", "rotate", "annotate", "markup", "substrata"],
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove flat or chroma-key backgrounds from images",
    category: "image",
    priority: "P1",
    icon: "Eraser",
    keywords: ["background", "remove", "transparent", "cutout", "chroma", "green screen"],
  },
  {
    id: "artwork-enhancer",
    name: "Artwork Enhancer",
    description: "Add a colour noise and grain overlay to artwork",
    category: "image",
    priority: "P3",
    icon: "Sparkles",
    keywords: ["artwork", "noise", "grain", "texture", "enhance", "overlay"],
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate a full favicon set from any image",
    category: "image",
    priority: "P1",
    icon: "Star",
    keywords: ["favicon", "icon", "ico", "apple touch", "manifest", "generate"],
  },
  {
    id: "image-clipper",
    name: "Image Clipper",
    description: "Trim transparent edges from PNGs to the smallest bounding box",
    category: "image",
    priority: "P2",
    icon: "Crop",
    keywords: ["clip", "trim", "transparent", "crop", "bounding box", "png"],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert between PNG, JPEG, WebP, BMP and ICO with resize options",
    category: "image",
    priority: "P0",
    icon: "Image",
    keywords: ["convert", "png", "jpeg", "webp", "bmp", "ico", "resize", "image"],
  },
  {
    id: "image-splitter",
    name: "Image Splitter",
    description: "Split an image into a grid of tiles",
    category: "image",
    priority: "P2",
    icon: "LayoutGrid",
    keywords: ["split", "tiles", "grid", "slice", "image", "cut"],
  },
  {
    id: "image-stitcher",
    name: "Image Stitcher",
    description: "Combine multiple images into one horizontally or vertically",
    category: "image",
    priority: "P2",
    icon: "Layers",
    keywords: ["stitch", "combine", "merge", "join", "collage", "image"],
  },
  {
    id: "image-tracer",
    name: "Image Tracer",
    description: "Trace raster images into SVG vector paths",
    category: "image",
    priority: "P2",
    icon: "PenTool",
    keywords: ["trace", "vector", "svg", "raster", "potrace", "convert"],
  },
  {
    id: "paste-image",
    name: "Paste Image",
    description: "Paste an image from your clipboard and download it",
    category: "image",
    priority: "P2",
    icon: "ImagePlus",
    keywords: ["paste", "clipboard", "image", "download", "screenshot"],
  },
  {
    id: "placeholder-generator",
    name: "Placeholder Generator",
    description: "Generate placeholder images at any size",
    category: "image",
    priority: "P2",
    icon: "Image",
    keywords: ["placeholder", "dummy", "mock", "image", "generate", "lorem picsum"],
  },
  {
    id: "svg-optimiser",
    name: "SVG Optimiser",
    description: "Optimise and minify SVG files",
    category: "image",
    priority: "P1",
    icon: "Image",
    keywords: ["svg", "optimise", "optimize", "minify", "svgo", "compress"],
  },
  {
    id: "matte-generator",
    name: "Matte Generator",
    description: "Put non-square images on a square matte for social posts",
    category: "image",
    priority: "P2",
    icon: "Frame",
    keywords: ["matte", "square", "instagram", "social", "pad", "letterbox"],
  },
  {
    id: "scroll-generator",
    name: "Seamless Scroll Generator",
    description: "Split a wide image into a seamless Instagram carousel",
    category: "image",
    priority: "P2",
    icon: "Layers",
    keywords: ["carousel", "instagram", "scroll", "seamless", "split", "social"],
  },
  {
    id: "social-cropper",
    name: "Social Media Cropper",
    description: "Crop images to Instagram, Bluesky, X and Threads presets",
    category: "image",
    priority: "P1",
    icon: "Crop",
    keywords: ["crop", "social", "instagram", "bluesky", "threads", "twitter", "preset"],
  },
  {
    id: "watermarker",
    name: "Watermarker",
    description: "Add text or image watermarks to your images",
    category: "image",
    priority: "P2",
    icon: "Droplet",
    keywords: ["watermark", "stamp", "copyright", "brand", "overlay", "image"],
  },

  // ── Typography & Text ─────────────────────────────────────────────────────
  {
    id: "doc-converter",
    name: "Document Converter",
    description: "Convert between Markdown, HTML, plain text and rich text",
    category: "typography",
    priority: "P1",
    icon: "FileText",
    keywords: ["document", "convert", "markdown", "html", "docx", "text", "rtf"],
  },
  {
    id: "font-explorer",
    name: "Font File Explorer",
    description: "Inspect font file metadata, glyphs and OpenType features",
    category: "typography",
    priority: "P2",
    icon: "Type",
    keywords: ["font", "otf", "ttf", "woff", "opentype", "glyphs", "metadata"],
  },
  {
    id: "glyph-browser",
    name: "Glyph Browser",
    description: "Browse and copy Unicode glyphs by block",
    category: "typography",
    priority: "P2",
    icon: "Type",
    keywords: ["glyph", "unicode", "character", "symbol", "emoji", "browse"],
  },
  {
    id: "large-type",
    name: "Large Type",
    description: "Text, but big — for reading numbers across the room",
    category: "typography",
    priority: "P3",
    icon: "Type",
    keywords: ["large", "big", "type", "display", "read", "zoom"],
  },
  {
    id: "line-height-calc",
    name: "Line Height Calculator",
    description: "Calculate optimal line height from font size and measure",
    category: "typography",
    priority: "P2",
    icon: "Ruler",
    keywords: ["line height", "leading", "typography", "calculate", "measure", "rhythm"],
  },
  {
    id: "paper-sizes",
    name: "Paper Sizes",
    description: "Reference for A, B, C, US and envelope paper dimensions",
    category: "typography",
    priority: "P3",
    icon: "FileText",
    keywords: ["paper", "size", "a4", "letter", "iso", "dimensions", "reference"],
  },
  {
    id: "px-to-rem",
    name: "PX to REM",
    description: "Convert between pixels, rem, em and percent",
    category: "typography",
    priority: "P1",
    icon: "Ruler",
    keywords: ["px", "rem", "em", "convert", "css", "unit", "root"],
  },
  {
    id: "markdown-editor",
    name: "Text Editor",
    description: "Distraction-free Markdown writer with live preview",
    category: "typography",
    priority: "P1",
    icon: "FileText",
    keywords: ["markdown", "editor", "writer", "distraction free", "preview", "notes"],
  },
  {
    id: "text-scratchpad",
    name: "Text Scratchpad",
    description: "Scratch text with case, sort, dedupe and trim tools",
    category: "typography",
    priority: "P2",
    icon: "StickyNote",
    keywords: ["scratchpad", "text", "manipulate", "case", "sort", "trim", "notes"],
  },
  {
    id: "typo-calc",
    name: "Typography Calculator",
    description: "Convert between points, picas, pixels, ems and millimetres",
    category: "typography",
    priority: "P2",
    icon: "Ruler",
    keywords: ["typography", "point", "pica", "em", "pixel", "convert", "units"],
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences and reading time",
    category: "typography",
    priority: "P1",
    icon: "Text",
    keywords: ["word", "count", "character", "sentence", "reading time", "statistics"],
  },
  {
    id: "shavian-transliterator",
    name: "Shavian Transliterator",
    description: "Transliterate English text into the Shavian alphabet",
    category: "typography",
    priority: "P3",
    icon: "Type",
    keywords: ["shavian", "transliterate", "alphabet", "phonetic", "english", "shaw"],
  },

  // ── Print & Production ────────────────────────────────────────────────────
  {
    id: "pdf-preflight",
    name: "PDF Preflight",
    description: "Analyse PDFs for print-readiness issues",
    category: "print",
    priority: "P2",
    icon: "Printer",
    keywords: ["pdf", "preflight", "print", "bleed", "trim", "cmyk", "check"],
  },
  {
    id: "print-imposer",
    name: "Print Imposer",
    description: "Impose PDF pages for booklet, saddle-stitch and N-up printing",
    category: "print",
    priority: "P2",
    icon: "Printer",
    keywords: ["impose", "booklet", "saddle stitch", "n-up", "pdf", "print", "signature"],
  },
  {
    id: "zine-imposer",
    name: "Zine Imposer",
    description: "Impose single-sheet zines: 8-page mini-zine and accordion folds",
    category: "print",
    priority: "P3",
    icon: "Printer",
    keywords: ["zine", "impose", "mini zine", "accordion", "fold", "8 page", "print"],
  },

  // ── Calculators ───────────────────────────────────────────────────────────
  {
    id: "sci-calc",
    name: "Scientific Calculator",
    description: "Full-featured scientific calculator with history",
    category: "calculate",
    priority: "P1",
    icon: "Calculator",
    keywords: ["calculator", "scientific", "math", "trig", "log", "compute"],
  },
  {
    id: "graph-calc",
    name: "Graph Calculator",
    description: "Plot and visualise mathematical functions",
    category: "calculate",
    priority: "P2",
    icon: "ChartLine",
    keywords: ["graph", "plot", "function", "chart", "math", "visualise", "curve"],
  },
  {
    id: "algebra-calc",
    name: "Algebra Calculator",
    description: "Symbolic algebra: simplify, expand, solve and derive",
    category: "calculate",
    priority: "P2",
    icon: "Calculator",
    keywords: ["algebra", "symbolic", "simplify", "factor", "solve", "derivative", "cas"],
  },
  {
    id: "time-calc",
    name: "Time Calculator",
    description: "Date arithmetic, duration maths and timezone conversion",
    category: "calculate",
    priority: "P1",
    icon: "Clock",
    keywords: ["time", "date", "duration", "timezone", "add", "subtract", "difference"],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, mass, area, volume, data, speed and temperature",
    category: "calculate",
    priority: "P0",
    icon: "ArrowLeftRight",
    keywords: ["unit", "convert", "length", "weight", "data", "temperature", "metric"],
  },

  // ── Other ─────────────────────────────────────────────────────────────────
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate Data Matrix, Aztec, PDF417, Code 128, EAN-13 and more",
    category: "generate",
    priority: "P2",
    icon: "Barcode",
    keywords: ["barcode", "data matrix", "aztec", "pdf417", "code128", "ean13", "upc"],
  },
  {
    id: "qr-styled",
    name: "Styled QR Generator",
    description: "Generate styled QR codes with custom colours, shapes and a logo",
    category: "generate",
    priority: "P1",
    icon: "QrCode",
    keywords: ["qr", "qrcode", "styled", "logo", "colour", "brand", "generate"],
  },
  {
    id: "cipher-decoder",
    name: "Cipher Decoder",
    description: "Decode classical ciphers manually or by auto-detection",
    category: "encode",
    priority: "P2",
    icon: "Lock",
    keywords: ["cipher", "caesar", "vigenere", "rot13", "atbash", "decode", "crack"],
  },
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate HTML meta, Open Graph and Twitter card tags",
    category: "generate",
    priority: "P1",
    icon: "Globe",
    keywords: ["meta", "og", "open graph", "twitter card", "seo", "html", "tags"],
  },
  {
    id: "tailwind-cheatsheet",
    name: "Tailwind Cheat Sheet",
    description: "Searchable quick reference for Tailwind utility classes",
    category: "inspect",
    priority: "P2",
    icon: "Wind",
    keywords: ["tailwind", "cheatsheet", "reference", "classes", "utility", "css"],
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOL_REGISTRY.find((t) => t.id === id);
}

export function getToolsByCategory(category: ToolDefinition["category"]): ToolDefinition[] {
  return TOOL_REGISTRY.filter((t) => t.category === category);
}

export function getToolsByPriority(priority: ToolDefinition["priority"]): ToolDefinition[] {
  return TOOL_REGISTRY.filter((t) => t.priority === priority);
}

export function searchTools(query: string): ToolDefinition[] {
  return fuzzySearchTools(query, TOOL_REGISTRY).map((r) => r.tool);
}

export { fuzzySearchTools, fuzzyMatch, type ToolSearchResult } from "./fuzzy-search";
