"use client";

import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  ArrowDataTransferHorizontalIcon,
  BarcodeIcon,
  BinaryIcon,
  BlendIcon,
  BracesIcon,
  BracketsIcon,
  Calculator01Icon,
  CalendarCheckIn01Icon,
  CaseSensitiveIcon,
  ChartLineIcon,
  CheckListIcon,
  Clock01Icon,
  CodeIcon,
  ColorPickerIcon,
  ColorsIcon,
  ComponentIcon,
  ComputerIcon,
  ComputerTerminal01Icon,
  ContrastIcon,
  CropIcon,
  Database01Icon,
  DivideSignIcon,
  DocumentCodeIcon,
  DropletIcon,
  DropperIcon,
  Eraser01Icon,
  EyeIcon,
  FileCodeIcon,
  FileDiffIcon,
  FileEmpty02Icon,
  FingerPrintIcon,
  FrameIcon,
  FunctionIcon,
  GitCompareIcon,
  Globe02Icon,
  HashIcon,
  HexagonIcon,
  Image01Icon,
  ImageAdd01Icon,
  Layers01Icon,
  LayoutGridIcon,
  LayoutThreeColumnIcon,
  LeftToRightListNumberIcon,
  Link01Icon,
  Link02Icon,
  LockIcon,
  PaintBoardIcon,
  PaintBrush04Icon,
  PenTool01Icon,
  PhpIcon,
  PrinterIcon,
  QrCodeIcon,
  RegexIcon,
  RulerIcon,
  Search01Icon,
  SearchVisualIcon,
  SecurityCheckIcon,
  Shield01Icon,
  ShuffleIcon,
  SourceCodeIcon,
  SparklesIcon,
  SqlIcon,
  StarIcon,
  StickyNote01Icon,
  StopWatchIcon,
  SwatchIcon,
  Table01Icon,
  TailwindcssIcon,
  TextFontIcon,
  TextIcon,
  Timer01Icon,
  Wrench01Icon,
  Xml01Icon,
} from "@hugeicons/core-free-icons";
import { cn } from "../lib/utils";

const ICONS: Record<string, IconSvgElement> = {
  ArrowLeftRight: ArrowDataTransferHorizontalIcon,
  Barcode: BarcodeIcon,
  Binary: BinaryIcon,
  ChartLine: ChartLineIcon,
  Contrast: ContrastIcon,
  Crop: CropIcon,
  Droplet: DropletIcon,
  Eraser: Eraser01Icon,
  Eye: EyeIcon,
  Eyedropper: DropperIcon,
  Frame: FrameIcon,
  Function: FunctionIcon,
  Gradient: BlendIcon,
  Layers: Layers01Icon,
  Printer: PrinterIcon,
  Ruler: RulerIcon,
  Swatch: SwatchIcon,
  Type: TextFontIcon,
  Wind: TailwindcssIcon,
  ColorPicker: ColorPickerIcon,
  Braces: BracesIcon,
  Brackets: BracketsIcon,
  Calculator: Calculator01Icon,
  CalendarCheck: CalendarCheckIn01Icon,
  CaseSensitive: CaseSensitiveIcon,
  Clock: Clock01Icon,
  Code: CodeIcon,
  Code2: SourceCodeIcon,
  Columns: LayoutThreeColumnIcon,
  Columns3: LayoutThreeColumnIcon,
  Component: ComponentIcon,
  Database: Database01Icon,
  FileCode: FileCodeIcon,
  FileCode2: DocumentCodeIcon,
  FileDiff: FileDiffIcon,
  FileJson: Xml01Icon,
  FileJson2: Xml01Icon,
  FileText: FileEmpty02Icon,
  Fingerprint: FingerPrintIcon,
  GitCompare: GitCompareIcon,
  Globe: Globe02Icon,
  Hash: HashIcon,
  Hexagon: HexagonIcon,
  Image: Image01Icon,
  ImagePlus: ImageAdd01Icon,
  LayoutGrid: LayoutGridIcon,
  Link: Link01Icon,
  Link2: Link02Icon,
  ListOrdered: LeftToRightListNumberIcon,
  ListTodo: CheckListIcon,
  Lock: LockIcon,
  Monitor: ComputerIcon,
  PaintBoard: PaintBoardIcon,
  Paintbrush: PaintBrush04Icon,
  Palette: ColorsIcon,
  PenTool: PenTool01Icon,
  PHP: PhpIcon,
  QrCode: QrCodeIcon,
  Regex: RegexIcon,
  ScanSearch: SearchVisualIcon,
  Search: Search01Icon,
  Shield: Shield01Icon,
  ShieldCheck: SecurityCheckIcon,
  Shuffle: ShuffleIcon,
  Slash: DivideSignIcon,
  Sparkles: SparklesIcon,
  Sql: SqlIcon,
  Star: StarIcon,
  StickyNote: StickyNote01Icon,
  Stopwatch: StopWatchIcon,
  Table: Table01Icon,
  Terminal: ComputerTerminal01Icon,
  Text: TextIcon,
  Timer: Timer01Icon,
  Wrench: Wrench01Icon,
};

interface ToolIconProps {
  name: string;
  className?: string;
  size?: number | string;
  strokeWidth?: number;
}

export function ToolIcon({ name, className, size = "1em", strokeWidth = 1.75 }: ToolIconProps) {
  const icon = ICONS[name] ?? Wrench01Icon;
  return (
    <HugeiconsIcon
      icon={icon}
      size={size}
      strokeWidth={strokeWidth}
      color="currentColor"
      aria-hidden
      className={cn("shrink-0 text-current", className)}
    />
  );
}
